//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWUDataExtractor.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NWUDataExtractor.Test.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAPTER 2. HEALTH SCIENCES 37
        ///2.2 8DJH01-G301P: Bachelor of Health Sciences with Physiology
        ///and Biochemistry(phasing in 2018)
        ///Year 1 Semester 1 (27)
        ///07:30 08:00 09:30 11:00 12:15 13:00 14:30 16:00 17:00
        ///08:00 09:15 10:45 12:15 12:45 14:15 15:45 17:15 17:45
        ///Optional Optional Optional
        ///Mo 5A 5A
        ///NCHE111a
        ///E3 -G20
        ///FSKS113b
        ///F3 -G10
        ///FSKS113b
        ///F3 -G10
        ///10
        ///FLGX113b
        ///N2A-G01
        ///FLGX113b
        ///F12-211
        ///FLGX113b
        ///F12-G14
        ///FLGX113b
        ///F12-211
        ///FLGX113b
        ///F12-G14
        ///FLGX113b
        ///F12-211
        ///FLGX113b
        ///F12-G14
        ///Tu 3B 3B 3A
        ///MTHS1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SinglePageSample {
            get {
                return ResourceManager.GetString("SinglePageSample", resourceCulture);
            }
        }
    }
}
